services:
#Initialize db service
  db: 
    image: mysql:8.0
    #Set the mysql environment variables
    environment: 
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bookapi
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
#Initialize the api service
  api:
    ports: 
     - 8000  #Expose on port 8000
    build:
      context: ./api
 #Set the environment variables     
    environment:
      DB_HOST: db
      DB_DATABASE: bookapi
      DB_USERNAME: app
      DB_PASSWORD: password
    networks:
      - app-network
    depends_on:
      - db
#Initialize the client service   
  client:
    ports:
      - 3000
    build:
      context: ./client
    environment:
      API_BASE_URL: http://api:8000/api
    networks:
      - app-network
    depends_on:
      - api
 #Initialize nginx open ports 80 for HTTP and 443 for HTTPS 
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443" 
 #mount volumes containing nginx.conf and certs     
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs  
    networks:
      - app-network
    depends_on:
      - client

volumes:
  db_data:

networks:
  app-network:

